### PR TITLE
Typo for BaseWaitingMessage in OperationTimer

### PR DESCRIPTION
**Pull request by Fruchtzwerg94**

### CODE REVIEW

**Comment by Fruchtzwerg94** [comment]
Hi @Platonenkov , is there any issue with the PR? You don't want to merge it?

**Comment by Platonenkov** [comment]
> Hi @Platonenkov , is there any issue with the PR? You don't want to merge it?
Hi, I honestly don't remember why I didn't add it:)
don't you think the translation is correct?

**Comment by Fruchtzwerg94** [comment]
> > Hi @Platonenkov , is there any issue with the PR? You don't want to merge it?
> 
> Hi, I honestly don't remember why I didn't add it:) don't you think the translation is correct?

Yes, "Calculation time" does not make sense here. "Calculating time" would be right.

**Comment by Platonenkov** [comment]
ok, it`s done
will update in next version, or is that critical to you?

**Comment by Fruchtzwerg94** [comment]
> ok, it`s done will update in next version, or is that critical to you?

Great to hear. Thanks. Not critical :-) ... I can wait for the next release. Thanks for asking!

**Pull request merged**
